### ISSUE TITLE
Multiple and different instalation process on the website

### ISSUE THREAD

**Issue by AltamiroAJ** [hkroeger/insightcae#13]
I was trying to install InsightCAE, however, I the same steps of instalation with differences between then, different links for the repository key, as well as different instalation names (-base vs -ce).

I assume that the website steps would be the most up to date however, the workbench didn't work, got a Shared Lib missing file error. it was the insightcae-ce install command, now I uninstalled it and I am trying the insightcae-base command.

I will report if the error is fixed.

**Comment by AltamiroAJ** [comment]
After a lot of digging I managed to fix the issue for libQt5Coreinsightcae.so.5 : cannot open shared fileobject file with the following command:

`sudo strip --remove-section=.note.ABI-tag /opt/insightcae/lib/libQt5Coreinsightcae.so.5`

**Comment by hkroeger** [comment]
Hi AltamiroAJ,

thank you for your report. Sorry for the confusion. Indeed, the instructions for WSL still show the outdated package name "-base". This has been changed to "-ce" in the latest release. We will update that.

From your second comment, I guess you indeed want to use the software within WSL. We have no other solution to this issue yet than what you have found. Unfortunately, you have to repeat that after every update again.

Regards, Hannes
