### ISSUE TITLE
Dependencies issue when installing from ubuntu 18.04 sub system on windows

### ISSUE THREAD

**Issue by AllanElleuch** [hkroeger/insightcae#14]
Hi, 

When I try to install the package "insightcae-base" I have the following message:

```

The following packages have unmet dependencies:
 insightcae-base : Depends: paraview5-offscreen-insightcae (= 5.6.69613) but 5.6.73001 is to be installed
                   Recommends: paraview5-insightcae but it is not going to be installed
```

Do you have any insight about  how to resolve the dependency? I used the following repository: http://downloads.silentdynamics.de/ubuntu

**Comment by hkroeger** [comment]
Dear Allan,

we have changed the packaging scheme with version 2 and the package "insightcae-base" is now outdated and no longer maintained.
You should install the package "insightcae-ce" instead.

Regards, Hannes
