### ISSUE TITLE
.../libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by workbench)

### ISSUE THREAD

**Issue by FraMiP** [hkroeger/insightcae#17]
Hi all,
I've installed InsightCAE as shown on your webpage and got following error message (using Ubuntu 20.04).
Thanks in advance for your help. Regards, Franz.

workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by workbench)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libtoolkit_gui.so)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libtoolkit_remote.so)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libinsightcad_gui.so)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libinsightcad.so)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libTKOffsetinsightcae.so.7)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libTKIGESinsightcae.so.7)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libTKXDESTEPinsightcae.so.7)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libTKSTEPinsightcae.so.7)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libTKXSBaseinsightcae.so.7)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libTKXCAFinsightcae.so.7)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libTKStdLinsightcae.so.7)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libTKBOinsightcae.so.7)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libTKBRepinsightcae.so.7)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libTKMathinsightcae.so.7)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libTKCDFinsightcae.so.7)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libtoolkit.so)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libwt.so.4.1.0)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libvtkFiltersExtraction-pvis.so.1)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libvtkCommonCore-pvis.so.1)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libvtkIOGeometry-pvis.so.1)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libvtkIOExport-pvis.so.1)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libvtkRenderingOpenGL2-pvis.so.1)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libvtksys-pvis.so.1)
workbench: /home/fpi/OpenFOAM/OpenFOAM-v2012/ThirdParty/platforms/linux64/gcc-6.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/insightcae/lib/libvtkjsoncpp-pvis.so.1)

**Comment by hkroeger** [comment]
I assume, you installed a binary package from the master repository ("downloads.silentdynamics.de/ubuntu") and you did not attempt to compile the software yourself?

This looks like a clash in the environment. The bashrc script of OF2012 seems to redirect the LD_LIBRARY_PATH to its own third party directory. And the libstdc++ there appears to be incompatible with the system one. One attempt would be to start the workbench without the OpenFOAM environment loaded.

Please note that we have not yet updated InsightCAE to the most recent OpenFOAM version and we haven't tested yet the coexistence.

**Comment by FraMiP** [comment]
Good morning Mr. Kröger,

yes, I did...like shown under the section "ubuntu" on your webpage (using the ubuntu focal-version 20.04). As I am not an expert in Linux/Ubuntu I thought the shown procedure would work. May I ask you when the appropriate installation routine would be available?

One more question on the current installation: as you stated, how can I start InsightCAE without the OpenFOAM environment loaded? (thought I've tried this by only inserting "workbench" into the terminal)

Thanks and regards,
Franz.

**Comment by hkroeger** [comment]
Hi Franz,

the installation procedure worked obviously, since all files seem to be in place ("/opt/insightcae").

I guess, for loading the possibly conflicting OpenFOAM-v2012 environment, you inserted some statement in your ~/.bashrc file like:

`source $HOME/OpenFOAM/OpenFOAM-v2012/etc/bashrc`

or similar.
For testing, you should disable this statement by putting a hash '#' in front and then open a new terminal.

**Comment by FraMiP** [comment]
Yes, all files seems to be in place ("/opt/insightcae"). I've disabled the comment line in .bashrc like shown, but following error message was shown:

```
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: linuxfb, minimal, offscreen, vnc, webgl, xcb.
Aborted (core dumped)
```

One additional information: yesterday I have tried to run following comment lines I found on google to fix the problem, could this be the reason for the new problem?
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install gcc-9
sudo apt install libstdc++6
```

Thanks in advance!

**Comment by hkroeger** [comment]
This indicates a problem with graphical output.

What kind of system are you running on? Is that a native Linux system or a WSL distribution?

**Comment by FraMiP** [comment]
WSL distribution (ubuntu) on windows10

**Comment by hkroeger** [comment]
Ok, I see.

This can be overcome. But there will be issues with graphical artifacts in the GUI. They appear as soon as the CAD preview window is displayed and we could not find a way to get rid of them.

Thus we have compiled a windows version of the GUI components and execute only the CFD tools in the WSL environment.
We have finished a first release very recently.
You can find the current version here: http://downloads.silentdynamics.de/ubuntu_dev/InsightCAEInstaller.exe
Please note that this is still WiP. If you note any issues, please let us know.
