### ISSUE TITLE
InsightCAE für Win10 geht nicht auf

### ISSUE THREAD

**Issue by munbehaun** [hkroeger/insightcae#20]
InsightCAE für Win10 geht nicht auf. Shell öffnet und schließt schnell wieder:
ImportError: cannot import name 'sysconfig' 
Warning: aptdoes not have a stable CLI interface. Use with caution in scripts.  
Auch InsightCAE WSL geht nicht auf: 
Traceback (most recent call last): 
 File "<string>", line 1, in <module>
ImportError: cannot import name 'sysconfig' 
root@DESKTOP-0BUUTDD:/mnt/c/Program Files (x86)/silentdynamics/InsightCAE WSL Environment 1.0.0#

**Comment by hkroeger** [comment]
Thanks for the report!

There seems to be a package missing in the installation.

Please try the following: Start the menu entry "InsightCAE WSL" and at the command prompt ("root@DESKTOP-0BUUTDD:/mnt/c/Program Files (x86)/silentdynamics/InsightCAE WSL Environment 1.0.0#") enter the following:
`apt install python3-distutils`

**Comment by munbehaun** [comment]
Danke für die schnelle Hilfe!  
Im InsightCAE WSL kommt jetzt keine Fehlermeldung mehr. (Aber es geht auch nichts auf, außer der Shell).
Leider kommt beim Öffnen von InsightCAE immer noch die Meldung: 
Warnung: apt hat keine stabile CLI-Schnittstelle. In Skripten mit Vorsicht verwenden. 
Und das InsightCAE - Fenster schließt sofort wieder.

**Comment by hkroeger** [comment]
I have put an updated installer into place now.

It should fix the two problems: the missing python package and the error in the backend version check.

Please remove the already installed InsightCAE package (in Control Panel / Apps&Features) and execute the updated installer. In the component list, you can deselect all the 3rd party dependencies (gnuplot etc.) Just reinstall the two InsightCAE components.
