### ISSUE TITLE
InsightCAE for Windows still does not work

### ISSUE THREAD

**Issue by munbehaun** [hkroeger/insightcae#21]
I tried the new download. First only the 2 InsightCAE packs. The programm opens, but it can not lounch ParaView.  
It also says: The backend package in the WSL environment is not of the same version as this GUI frontend. 
(GUI version 3.0.146-g1caeed1b (next release), WSL version: 3.0.1g2ca3579b ()) 
I executed the Update, but there was an error: 
E: unable to locate package insightcae

**Comment by munbehaun** [comment]
Today I installed all again, but I have the same errors.

**Comment by munbehaun** [comment]
Ja, habe ich versucht.  Standardmäßig ist oben eingestellt: run on remote host: damit lief das Programm los, zeigte aber immer Status = -1, result = 0;  ... und ich habe ja keinen remote host. 
Wenn ich das kreuz dort raus nehme, kommt gleich: 
An error has occured: 
OFEs::get(): Requested OpenFOAM environment OFesi1806 is undefined. 
(Check environment variable INSIGHT_OFES) ....

**Comment by hkroeger** [comment]
> Status = -1, result = 0; ... und ich habe ja keinen remote host.
Doch, in Windows läuft OpenFOAM in einer WSL-Instanz und die Kommunikation läuft über das Netzwerk. Die WSL-Instanz ist dann der "Remote Host". Ohne das Kreuz geht es nicht.

**Comment by munbehaun** [comment]
OK, also habe ich es nochmal mit dem Kreuzchen laufen lassen. Es läuft eine Zeit lang immer mit der Meldung: 
httpResponse err=system:10061, crq=0, status=-1, success=0 
+------------------------------ Warning follows -------------------------------+
|                                                                              |
| Could not detect any usable OpenFOAM environment. Running remote command     |
| with no OpenFOAM environment loaded.                                         |
|                                                                              |
+------------------------------------------------------------------------------+


+============================= *** ERROR [1] *** ==============================+
|                                                                              |
| in step 3:                                                                   |
|  Could not contact analysis server after launching it!                       |
|                                                                              |
+------------------------------------------------------------------------------+

**Comment by munbehaun** [comment]
Dann geht ein Fehler-Fenster auf: 
![image](https://user-images.githubusercontent.com/64554896/143265572-8d48d282-f17f-4a0c-b72d-bfafd2740d07.png)

**Comment by munbehaun** [comment]
0# 0x6249B557 in C:\Program Files (x86)\silentdynamics\InsightCAE 3.0.146\bin\libtoolkit.dll
1# 0x6249BC8E in C:\Program Files (x86)\silentdynamics\InsightCAE 3.0.146\bin\libtoolkit.dll
2# 0x001D7C38 in C:\Program Files (x86)\silentdynamics\InsightCAE 3.0.146\bin\workbench.exe
3# 0x001D7F5A in C:\Program Files (x86)\silentdynamics\InsightCAE 3.0.146\bin\workbench.exe
4# 0x640AABF3 in C:\Program Files (x86)\silentdynamics\InsightCAE 3.0.146\bin\libtoolkit_gui.dll
5# 0x6248CC13 in C:\Program Files (x86)\silentdynamics\InsightCAE 3.0.146\bin\libtoolkit.dll
6# 0x63D629FB in C:\Program Files (x86)\silentdynamics\InsightCAE 3.0.146\bin\libboost_thread-mt.dll
7# 0x75246CFF in C:\WINDOWS\System32\msvcrt.dll
8# 0x75246DC1 in C:\WINDOWS\System32\msvcrt.dll
9# 0x750BFA29 in C:\WINDOWS\System32\KERNEL32.DLL
10# 0x77007A9E in C:\WINDOWS\SYSTEM32\ntdll.dll
11# 0x77007A6E in C:\WINDOWS\SYSTEM32\ntdll.dll

**Comment by hkroeger** [comment]
Ist bei der Installation ein Dialogfenster aufgepoppt, dass nach einer Firewall-Ausnahme für die WSL-Instanz gefragt hat? Haben Sie die Ausnahme zugelassen oder abgelehnt?

**Comment by munbehaun** [comment]
Bei der ersten Installation ist mir da vieles aufgefallen. 
![image](https://user-images.githubusercontent.com/64554896/143266870-62b22c82-5024-41e3-a86f-a4a3f4dce834.png)
Das habe ich zugelassen. 
Bei der dritten Installation jetzt ist mir sowas nicht aufgefallen.

**Comment by munbehaun** [comment]
Aber wenn die Frage nochmal kam, habe ich den Zugriff auch zugelassen.

**Comment by munbehaun** [comment]
Bei der ersten Installation hat dieser Schritt "Windows configures InsightCAE WSL Environment" sehr lange gedauert (ca.10-20min). Bei den nachfolgenden Installationen ging alles viel schneller. 
Ich habe auch nirgends den "Knopf" gefunden, wo ich die alte Installation löschen sollte: 
"Please remove the already installed InsightCAE package (in Control Panel / Apps&Features) "  
Wo wäre dieses "Control Panel"?

**Comment by munbehaun** [comment]
Korrektur: Bei den folgenden Installationen ging alles viel schneller. 
Ich habe auch den "Knopf" NICHT gefunden,

**Comment by munbehaun** [comment]
![image](https://user-images.githubusercontent.com/64554896/143270966-8d537898-3aef-461c-b1bb-4d66d20cfa9f.png)

**Comment by hkroeger** [comment]
Die Ausgaben im letzten Screenshot sind kein Problem, das können Sie ignorieren.

Ich habe versucht, ihr Problem zu reproduzieren und bin auf ein paar Probleme mit der Client-/Server-Kommunikation gestoßen. Ich werden das beheben und dann melde ich mich noch einmal.

**Comment by munbehaun** [comment]
Super, danke!

**Comment by hkroeger** [comment]
Ich habe jetzt einige Überarbeitungen an der Client-Server-Kommunikation vorgenommen und denke, dass es jetzt funktionieren sollte.
Auch Paraview sollte sich jetzt starten lassen.
Ein Update liegt hier bereit: http://downloads.silentdynamics.de/ubuntu_dev/
Ein paar Probleme des Installers sind noch nicht behoben:
* paraview.exe muss im PATH sein
* gnuplot.exe muss auch manuell zum PATH hinzugefügt werden

**Comment by munbehaun** [comment]
Hallo, ich habe alles neu installiert. MikTex hat gemotzt, weil die directory nicht leer war. Hab alles dort gelöscht, dann ging es.   Paraview öffnet jetzt, auch aus dem InsightCAE heraus. Aber die Berechnung läuft noch nicht.  
![image](https://user-images.githubusercontent.com/64554896/145069076-63595aab-1f8f-4537-9b1f-d032783f99cd.png)

**Comment by munbehaun** [comment]
0# 0x6360B637 in C:\Program Files (x86)\silentdynamics\InsightCAE 3.0.170\bin\libtoolkit.dll
1# 0x6360BE74 in C:\Program Files (x86)\silentdynamics\InsightCAE 3.0.170\bin\libtoolkit.dll
2# 0x00B9CBFA in C:\Program Files (x86)\silentdynamics\InsightCAE 3.0.170\bin\workbench.exe
3# 0x00BDD354 in C:\Program Files (x86)\silentdynamics\InsightCAE 3.0.170\bin\workbench.exe
4# 0x61A976BD in C:\Program Files (x86)\silentdynamics\InsightCAE 3.0.170\bin\libwt.dll
5# 0x604FF997 in C:\Program Files (x86)\silentdynamics\InsightCAE 3.0.170\bin\libstdc++-6.dll
6# 0x75246CFF in C:\WINDOWS\System32\msvcrt.dll
7# 0x75246DC1 in C:\WINDOWS\System32\msvcrt.dll
8# 0x750BFA29 in C:\WINDOWS\System32\KERNEL32.DLL
9# 0x77007A9E in C:\WINDOWS\SYSTEM32\ntdll.dll
10# 0x77007A6E in C:\WINDOWS\SYSTEM32\ntdll.dll

**Comment by hkroeger** [comment]
Die Ausgaben des Servers sollten im Tab "run" angezeigt werden.
Können Sie die auch mal schicken?

**Comment by hkroeger** [comment]
> Hallo, ich habe alles neu installiert. MikTex hat gemotzt, weil die directory nicht leer war. Hab alles dort gelöscht, dann ging es. Paraview öffnet jetzt, auch aus dem InsightCAE heraus. Aber die Berechnung läuft noch nicht. ![image](https://user-images.githubusercontent.com/64554896/145069076-63595aab-1f8f-4537-9b1f-d032783f99cd.png)

Bei einem Update brauchen Sie nur die (vorletzte) Komponente "InsightCAE" auswählen. Das WSL-Backend sollte dann über die GUI aktualisiert werden.

**Comment by munbehaun** [comment]
Im Reiter "RUN" wird gar nichts angezeigt. Da ist alles ganz leer.

**Comment by munbehaun** [comment]
Sorry. Im Reiter "Output" wird gar nichts angezeigt. Da ist alles ganz leer.

**Comment by munbehaun** [comment]
STL::build() [anonymous_Feature]: BEGIN
STL::build() [anonymous_Feature]: END 0.597734s wall, 0.593750s usr + 0.000000s sys = 0.593750s CPU (99.3%)
Box::build() [anonymous_Feature]: BEGIN
Box::build() [anonymous_Feature]: END 0.001119s wall, 0.000000s usr + 0.000000s sys = 0.000000s CPU (n/a%)
Cache contains 0 entities.
STL::build() [anonymous_Feature]: BEGIN
STL::build() [anonymous_Feature]: END 0.001252s wall, 0.000000s usr + 0.000000s sys = 0.000000s CPU (n/a%)
Box::build() [anonymous_Feature]: BEGIN
Box::build() [anonymous_Feature]: END 0.000452s wall, 0.000000s usr + 0.000000s sys = 0.000000s CPU (n/a%)
Cache contains 2 entities.
STL::build() [anonymous_Feature]: BEGIN
STL::build() [anonymous_Feature]: END 0.599583s wall, 0.578125s usr + 0.015625s sys = 0.593750s CPU (99.0%)
Box::build() [anonymous_Feature]: BEGIN
Box::build() [anonymous_Feature]: END 0.000989s wall, 0.000000s usr + 0.000000s sys = 0.000000s CPU (n/a%)
Cache contains 0 entities.
################################################################################

+------------------------------ Warning follows -------------------------------+
|                                                                              |
| Could not detect any usable OpenFOAM environment. Running remote command     |
| with no OpenFOAM environment loaded.                                         |
|                                                                              |
+------------------------------------------------------------------------------+

################################################################################

+============================= *** ERROR [1] *** ==============================+
|                                                                              |
| Could not contact analysis server after launching it!                        |
|                                                                              |
+------------------------------------------------------------------------------+

**Comment by hkroeger** [comment]
Ich habe jetzt noch einmal eine größere Überarbeitung vorgenommen. Ein entsprechendes Update liegt bereit.
Zur Info: die Erstellung des WSL-Backends ist jetzt aus dem Installer raus (war die letzte Komponente in der Liste) und wird jetzt zusammen mit den Suchpfaden zu den Thirdparty-Tools beim ersten Start der Workbench überprüft bzw. getriggert.

**Comment by munbehaun** [comment]
D.h,. ich lade den Installer neu runter, und installiere nur InsightCAE?

**Comment by hkroeger** [comment]
Genau.

**Comment by munbehaun** [comment]
Muss ich denn bei dem Touran.stl selbst die Straße dazu modellieren im CAD und auch das Volumen im Windkanal? Oder genügt das STL-file vom Touran, und der Rest wird von InsightCAE dazu modelliert?

**Comment by munbehaun** [comment]
![image](https://user-images.githubusercontent.com/64554896/147105904-d51d121c-6068-420d-af9f-a526f3e1a35f.png)

**Comment by munbehaun** [comment]
Soll ich Yes drücken?

**Comment by munbehaun** [comment]
![image](https://user-images.githubusercontent.com/64554896/147108013-0951cbaf-b037-4d31-8c72-b10e4d800c19.png)

**Comment by munbehaun** [comment]
![image](https://user-images.githubusercontent.com/64554896/147108235-1141d1ec-b23a-44c1-addd-8a6bcd4555d8.png)

**Comment by munbehaun** [comment]
![image](https://user-images.githubusercontent.com/64554896/147108299-834a2392-9245-4c66-af73-17435dc773c0.png)

**Comment by munbehaun** [comment]
![image](https://user-images.githubusercontent.com/64554896/147108421-83e8fbb2-5ef3-4d5f-8355-43f36bc1fc40.png)

**Comment by munbehaun** [comment]
![image](https://user-images.githubusercontent.com/64554896/147109062-dae541a9-5220-4194-add3-931caf8e3970.png)

**Comment by munbehaun** [comment]
![image](https://user-images.githubusercontent.com/64554896/147112334-b99f7300-8b84-415a-a94a-95bd09e6f0a7.png)
So weit war ich noch nie!

**Comment by munbehaun** [comment]
![image](https://user-images.githubusercontent.com/64554896/147112796-d92f9ead-b246-4b05-a689-cbbfa7439f51.png)
Viele Warnungen....

**Comment by munbehaun** [comment]
![image](https://user-images.githubusercontent.com/64554896/147113622-b0111534-bacc-4a7f-a81f-348d61788bbb.png)
Läuft!  Danke!

**Comment by hkroeger** [comment]
Ok, scheint ja geklappt zu haben.

Die Installation wird gerade noch weiter vereinfacht und dann auch dokumentiert. Update folgt in Kürze.
