### ISSUE TITLE
Permission denied for boost during report creation

### ISSUE THREAD

**Issue by wisehart** [hkroeger/insightcae#22]
Hi,

I am running InsightCAE (Version 3.0.1-g2ca3579b (HEAD)) on Linux Mint. Installed it from the ubuntu binaries repo as specified in the manual.

I set up a 2dAirfoilPolar case and in runs successfully. But when I try to produce the report, I get this error from boost:

+================================ ***ERROR*** =================================+
|                                                                              |
| boost::filesystem::create_directory: Permission denied:                      |
| "/20211213154742__4a4b"                                                      |
|                                                                              |
+------------------------------------------------------------------------------+

I think it tries to make a directory somewhere in the root filesystem and does not have root permissions.

**Comment by hkroeger** [comment]
Hi wisehart,
thanks for the report.
It appears that the software tries to create a temporary directory in the (non-writable) root directory.
Is it possible that the TMPDIR environment variable might be messed up? I'll check in due course for possible other causes.

Do you have a full console log for me?

**Comment by wisehart** [comment]
Hi,

I tried again this morning and now there are several things happening now:

It now ends with a map::at error:

`

+================================ ***ERROR*** =================================+
|                                                                              |
| map::at                                                                      |
|                                                                              |
+------------------------------------------------------------------------------+
`

Also some other functions do not work anymore. I changed the working directory, but the OpenFoam folders are sitll created in the old place. Also, the "clean" button in the GUI does not work anymore. I attached the console log.
[run_log.log](https://github.com/hkroeger/insightcae/files/7710531/run_log.log)

**Comment by hkroeger** [comment]
OK, thanks for the log.

The displayed error is misleading and just a follow-up error. The actual problem is recognizable in the log  (below: **ModuleNotFoundError: No module named 'Insight'**).
There is something messed up with the python path.

I haven't used the airfoil simulation for quite a while. It obviously needs some maintenance.
I will update it's result image rendering code to some updated method without the need for pvbatch asap and get back to you once this is done.

Regards

```

env -i DISPLAY=:0 HOME=/home/projects USER=projects SHELL=/bin/bash LANG=en_US.UTF-8 bash -lc source /opt/insightcae/bin/insight_setenv.sh;source insight.bashrc.of1806;cd "/home/projects/CFD/InsightCAE_Examples/subcase__geometry_alpha=5";pvbatch-offscreen "--force-offscreen-rendering" "/home/projects/CFD/InsightCAE_Examples/Airfoil2d_TL_180/042217280.py" 
Executing env
[E] Traceback (most recent call last):
[E]   File "/home/projects/CFD/InsightCAE_Examples/Airfoil2d_TL_180/042217280.py", line 1, in 
[E]     from Insight.Paraview import *
[E] ModuleNotFoundError: No module named 'Insight'

+------------------------------ Warning follows -------------------------------+
|                                                                              |
| An exception has occurred while processing the instance                      |
| subcase__geometry_alpha=5 of the parameter study.The analsis of this         |
| instance was not completed.                                                  |
| Reason: Execution of external application                                    |
| "pvbatch-offscreen "--force-offscreen-rendering"                             |
| "/home/projects/CFD/InsightCAE_Examples/Airfoil2d_TL_180/042217280.py""      |
| failed with return code 1!                                                   |
| Error output was:                                                            |
|                                                                              |
| Traceback (most recent call                                                  |
| last):                                                                       |
|   File                                                                       |
| "/home/projects/CFD/InsightCAE_Examples/Airfoil2d_TL_180/042217280.py", line |
| 1, in                                                                |
|     from Insight.Paraview import *                                           |
| ModuleNotFoundError: No                                                      |
| module named 'Insight'                                                       |
|                                                                              |
|                                                                              |
| The error occurred                                                           |
| while running OpenFOAM                                                       |
| analysis                                                                     |
| while executing command "pvbatch-offscreen                                   |
| "--force-offscreen-rendering"                                                |
| "/home/projects/CFD/InsightCAE_Examples/Airfoil2d_TL_180/042217280.py""      |
|                                                                              |
+------------------------------------------------------------------------------+


+================================ ***ERROR*** =================================+
|                                                                              |
| map::at                                                                      |
|                                                                              |
+------------------------------------------------------------------------------+
```

**Comment by hkroeger** [comment]
I have updated the VTK rendering part in the airfoil app and put an update into our development repository ( http://downloads.silentdynamics.de/ubuntu_dev/ ).
This should now no longer need python for the rendering part.

**Comment by wisehart** [comment]
Switched into dev ppa and got your fix! Works like a charm. Thank you very much.
