### ISSUE TITLE
"ParaView" findet Ergebnisse nicht

### ISSUE THREAD

**Issue by munbehaun** [hkroeger/insightcae#23]
Ich konnte 2 Berechnungen mit verschiedenen Geometrien machen, bekomme auch die PDF-Reports. Wenn ich aber 'ParaView' öffnen möchte, um die Ergebnisse anders darzustellen (Streamlines, ...), finde das Programm die Ergebnisfiles nicht. 
Ich habe in "Local working directory" einen Pfad angegeben: D:/Daten/PKW/Touran_A1/CAE1. 
Der bleibt aber leer

**Comment by munbehaun** [comment]
![image](https://user-images.githubusercontent.com/64554896/147216979-39e5e1a9-fcbb-49ce-87aa-a3b07393b93c.png)
Vielleicht liegt das noch an Windows / Linux Unterschied 'Slash' /und\ 'Backslash'

**Comment by munbehaun** [comment]
Ich kann das leider nicht von Hand ändern. Ich kann nur den Pfad auswählen und 'insightCAE' setzt dan die Pfade automatisch. Das ist auch beim Pfad für 'iscad' so, den das System nicht selbst gefunden hatte: 
![image](https://user-images.githubusercontent.com/64554896/147220165-61603170-136d-4efd-92ac-28da2f8bc470.png)

**Comment by hkroeger** [comment]
Ich denke, folgende Dinge sollte ich dazu noch sagen:

- Das Arbeitsverzeichnis in der WSL-Umgebung ist standardmäßig temporär und wird nach dem Ende des Solverlaufs und dem Erstellen der Auswertung gelöscht. (Im Moment haben wir die Windows-Version nur mit einer sehr kurz laufenden Simulationen verwendet, bei der der Kunde auch keinen Wert auf eine Paraview-Auswertung legt)
- Das entfernte Arbeitsverzeichnis (in der WSL-Umgebung) wird auch nicht in den lokalen Arbeitsordner kopiert
- Entsprechende Schalter, um das Verhalten zu ändern kommen mit einem der nächsten Updates
- Nur wenn man ein vorhandenes "Remote Directory" auswählt, wird es behalten
- Paraview geht also nur, während der Solver läuft
- Remote-Terminal geht momentan nur in Linux (In Windows muss man etwas umständlich eine Powershell aufmachen, mit "wsl -d insightcae-ubuntu-1804" eine bash-Shell starten und dann in das entsprechende Arbeitsverzeichnis wechseln

**Comment by munbehaun** [comment]
Vielen Dank für die Antwort und die verbesserten Versionen. Ich bekomme ja Ergebnisse, und damit ist mir schon viel geholfen. Eine bessere Darstellung der Stromlinien wäre hat noch schön gewesen, aber nicht so dringend.  Dann warten wir auf das Update.  
Vielen Dank nochmal und frohe Weihnachten, Martin U.

**Comment by hkroeger** [comment]
In Version 3.0.200 gibt es jetzt die Option, den Case nach Abschluss in den Arbeitsordner zu kopieren und zu behalten:
http://downloads.silentdynamics.de/ubuntu_dev/InsightCAEInstaller-3.0.200.exe
Wenn der (lokale) Arbeitsordner temporär ist, wird nichts kopiert; wenn der Arbeitsordner ein vorhandener Ordner ist, wird nach Abschluss der Berechnung standardmäßig alles aus dem WSL in den Arbeitsordner kopiert.

Hinweis: das WSL-Backend-System habe ich noch etwas geändert. Sie sollten vor dem Update die bestehende WSL-Distribution insightcae-ubuntu-1804 manuell entfernen, siehe hier: https://docs.microsoft.com/en-us/windows/wsl/basic-commands
Und auch die InsightCAE-Konfigurationsdatei löschen (c:\users\<user name>\.insight\share\remoteServers.list)
Beim ersten Programmstart wird dann das WSL-Backend wieder neu erzeugt. Das geht jetzt auch schneller als vorher.

**Comment by munbehaun** [comment]
Danke! Ich habe die WSL-Distributionen Insightcae-ubuntu-1804 und Insightcae-ubuntu-1804_1  manuell entfernt durch wsl --unregister insightcae-ubuntu-1804 ... ich hoffe, das war richtig. Dann habe ich "remoteservers.list" entfernt. Dort gibt es auch noch "externalPrograms.list". Muss das auch entfernt werden? Hab ich jetzt nicht gemacht. 
Jetzt installiere ich neu.

**Comment by munbehaun** [comment]
Die Rechnung läuft wieder, und es werden jetzt viele Daten in den Arbeitsordner geschrieben. Aber ein ParaViewStateFile .pvsm habe ich dort nicht gefunden.

**Comment by hkroeger** [comment]
Das Statefile ist optional

**Comment by munbehaun** [comment]
Ja, danke. Ich konnte ParaView öffnen und versuche nun eine gute Darstellung hin zu bekommen. Funktioniert alles.

**Comment by munbehaun** [comment]
Ich komme jetzt gut zurecht, und kann im ParaView alle Einstellungen so wählen, dass die Darstellungen für mich passen.  
Vielen Dank! Das ist jetzt so wirklich ein sehr hilfreiches Paket für mich.
