### ISSUE TITLE
Error Building Case with isofCaseBuilder

### ISSUE THREAD

**Issue by elitewill1200** [hkroeger/insightcae#24]
I have installed insightcae-ce using apt on ubuntu 20.04 as descibed in the docuemtnation.
I was following a simple tutorial to build a case and every time it runs into the same issue

```
from Insight.toolkit import *
ModuleNotFoundError: No module named 'Insight'
```
It appears the python module didn't install correctly. This error is also thrown when trying to import the insight toolkits into python3.8. I tried installing Insight with
```
pip install Insight
```
it seemed successful but the error persists

**Comment by elitewill1200** [comment]
Added traceback for clarificuation:
```
Traceback (most recent call last):
  File "/opt/insightcae/bin/isofRun.py", line 6, in <module>
    from Insight.toolkit import *
ModuleNotFoundError: No module named 'Insight'
```
it seems to be failing right as snappyHexMeshConfiguration is starting

I also just ran
```
sudo apt install insighttoolkit4-python3
```
to see if that works. No dice...

**Comment by hkroeger** [comment]
Hi,

the package "insighttoolkit4-python3" has nothing to do with InsightCAE.

Please try installing our development package first. I recently made some changes in the python integration.

The steps for installing from the development repo are the same as outlined on our website but you need to replace the URL with:

> $ sudo add-apt-repository http://downloads.silentdynamics.de/ubuntu_dev

(note the "_dev" suffix in the URL)
Please let me know, if that changed something.

**Comment by elitewill1200** [comment]
Hello,

The install has actually been running in since your last email background,
I added the dev branch after your suggestion but my internet is taking a
while. Anywho I added the issue on GitHub as well. I'll let you know if
that works through email and GitHub, thanks!

-William

**Comment by elitewill1200** [comment]
I installed the development package on a fresh install of Ubuntu, the same error occurred when hitting run. 
[TestCase.zip](https://github.com/hkroeger/insightcae/files/8017689/TestCase.zip)
here is the test case I am trying

**Comment by hkroeger** [comment]
Ok, thanks for the feedback.

I will check your case and get back in due course.

**Comment by hkroeger** [comment]
I found the issue:

in the file /opt/insightcae/bin/insight_setenv.sh, line 45 should be changed from

    if which python >/dev/null 2>&1; then

to

    if which python3 >/dev/null 2>&1; then

I will schedule that fix in the next rebuild.

**Comment by hkroeger** [comment]
By the way:

I corrected three issues in your input file "test.iscb":
1. there were two "Numerics" case elements added (MeshingNumerics and steadyIncompressibleNumerics). You dont' need MeshingNumerics. This is only needed, if you want to create an OpenFOAM case only for running e.g. snappyHexMesh and without any solver configuration (if you want to assemble a mesh from a set of simpler, indiviually created meshes)
2. reduced the maximum refinement level on the geometry.
3. changed the sign of the velocity at the inlet. It was directed out of the domain as you set it up.

Please find the file with corrections attached.
[test_modified.iscb.zip](https://github.com/hkroeger/insightcae/files/8026806/test_modified.iscb.zip)

![Auswahl_038](https://user-images.githubusercontent.com/2007077/153060187-1fd8d3a6-0c4b-4fd1-8069-bd71b400e49d.png)
