### ISSUE TITLE
runs with 6 CPUs, but not with 8 / 12

### ISSUE THREAD

**Issue by j2l** [hkroeger/insightcae#26]
Since cores are used at various moments by Ubuntu OS, I usually run `mpirun -np 8 (or 10) --oversubscribe` and it goes through, but using insightcae (without oversubscribe) snappyhexMes has to see idle CPUs. Would it be possible to add the option `--oversubscribe`?

**Comment by hkroeger** [comment]
The arguments for mpirun are hardcoded for now (in file src/toolkit/openfoam/openfoamcase.cpp, line 756 and 779).

Additional arguments could be specified using a mpirun wrapper script for example.

I will add the possibility for changing the mpirun command line.

**Comment by j2l** [comment]
Great! Thanks
`--oversubscribe` could be easy to add and takes care of anything if you want.

**Comment by hkroeger** [comment]
added in 4.0.15 (next-release commit 5ff8815555): further arguments to mpirun command line can be specified by environment variable INSIGHT_ADDITIONAL_MPIRUN_ARGS
