### ISSUE TITLE
No WSL Backend message

### ISSUE THREAD

**Issue by deandroberts** [hkroeger/insightcae#27]
I'm attempting to install InsightCAE.  After installing everything in the installation file I launched Workbench and got as far as Creating or Selecting Existing WSL Backend.  I don't know how to answer the questions to Create and new one and I don't know where to look to find an existing one.  See the attached image.  What should I do?
![Screenshot 2022-04-11 191728](https://user-images.githubusercontent.com/103473389/162866180-e6ed23e5-a366-424b-91e6-1669d99ee48a.png)

**Comment by hkroeger** [comment]
Hi Dean,

This is a bug. The Url should be automatically preset. We'll fix it ASAP.
For now, please try inserting this Url manually:
http://downloads.silentdynamics.de/ubuntu

**Comment by hkroeger** [comment]
No, this is no issue.

Just a warning that appears when  the backend version is checked during startup.

**Comment by deandroberts** [comment]
Then I'm good to go.  Thanks!
