### ISSUE TITLE
release? which dev version is latest? swrast?

### ISSUE THREAD

**Issue by j2l** [hkroeger/insightcae#32]
I finally understood how to run your dev images but 4.0.6 throws:
`libGL error: failed to load driver: swrast`
First, I wonder if 4.0.6 is before or after 4.0.21, I didn't find a changelog or mention of versions in commits, I guess I'm not fully awake this morning :)
Is you release still in May?
Thank you and have a great day

**Comment by hkroeger** [comment]
Dear Philipp,

4.0.21 is newer than 4.0.6.

And version 4 is the new release from this year.

Which command did you run when the error was emitted? Which OS?

Regards, Hannes

**Comment by j2l** [comment]
thank you @hkroeger 
`workbench`
Ubuntu 18.04 in a container.
v4 is out? I don't see it.

**Comment by j2l** [comment]
Still happening with 4.0.21
running container as user (1000)
workbench opens, I choose "numerical wind tunnel" and it crashes with:
```
user@fd9935b5cd9f:/$ workbench
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-user'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

**Comment by hkroeger** [comment]
So the application starts and if you create a new analysis, the program crashes?

What happens then is that an OpenGL based OpenCASCADE viewer is initialized. Looks like this is having some problems with your graphics setup.
Is the container on a Linux host? I never tried to run graphics stuff in such an configuration. I tried to run it in a WSL environment with an X server and this caused graphics problems all over the place.

**Comment by j2l** [comment]
Insightcae seems to run fine on the host, so I guess it's the container stuff.
is there any .desktop file content somewhere?

**Comment by j2l** [comment]
Just to know about the container stuff :)

**Comment by hkroeger** [comment]
> > Is the container on a Linux host?
> 
> Yes, Ubuntu 21.10 insightcae 3 was working fine though.
> 
> So your ubuntu18.04 on the _dev section is not to run as a container?

I use it without container on Linux:
1) I used to run the Software on HPC clusters and the clusters which I know don't support containers.
2) Not sure about the GUI stuff. Obviously, there are issues with the hardware acceleration. Also I think the user experience is a bit unfamiliar (e.g. File>open does not show the same filesystem as the host)

**Comment by hkroeger** [comment]
BTW: there are some .desktop templates in src/desktop. Though they are not yet included in the installer.
