### ISSUE TITLE
Workbench/Write+Stop stuck (win platform)

### ISSUE THREAD

**Issue by boucaron** [hkroeger/insightcae#34]
Hi,

I tried to recreate the basic numerical wind tunnel (with different geometries, same behavior)
I ran the windows version 5.0.2-g85ac383b (master)

When I click on the Write+Stop, it is stuck on 'Inserting derived input quantities into report'/'Computing projected area'

Follows the log:

<<
Solver run progress: 42.8%

127.0.0.1 - - [2024-Mar-03 21:36:40.495] "GET /all HTTP/1.1" 200 3736
smoothSolver:  Solving for Ux, Initial residual = 7.9417307e-05, Final residual = 3.9293982e-06, No Iterations 2
smoothSolver:  Solving for Uy, Initial residual = 0.0026120338, Final residual = 0.00015582713, No Iterations 2
smoothSolver:  Solving for Uz, Initial residual = 0.00067297578, Final residual = 4.2702657e-05, No Iterations 2
GAMGPCG:  Solving for p, Initial residual = 0.0016222989, Final residual = 2.9477223e-06, No Iterations 2
time step continuity errors : sum local = 0.00028552603, global = -4.8429393e-06, cumulative = 0.071911047
smoothSolver:  Solving for omega, Initial residual = 6.0014986e-06, Final residual = 2.9450323e-07, No Iterations 2
smoothSolver:  Solving for k, Initial residual = 0.00017911737, Final residual = 9.2347917e-06, No Iterations 2
bounding k, min: -0.030978192 max: 64.530765 average: 7.5238944
127.0.0.1 - - [2024-Mar-03 21:36:41.498] "GET /all HTTP/1.1" 200 1156
ExecutionTime = 408.55 s  ClockTime = 409 s

forces unnamed write:
    Sum of forces
        Total    : (0.040212826 -3.5191004e-05 0.058594027)
        Pressure : (0.038454967 -2.4328413e-05 0.058095364)
        Viscous  : (0.0017578589 -1.0862592e-05 0.00049866254)
    Sum of moments
        Total    : (-2.2447793e-07 -0.00050024972 -5.5192631e-07)
        Pressure : (-2.6145399e-07 -0.00050796455 -4.9921107e-07)
        Viscous  : (3.6976061e-08 7.7148312e-06 -5.2715237e-08)

End

Finalising parallel run
127.0.0.1 - - [2024-Mar-03 21:36:42.505] "GET /all HTTP/1.1" 200 867
Overall progress: 71.4286%
Overall: Finalizing solver run
Overall: Running reconstructPar for latest time step
env -i HOME=/home/user USER=user SHELL=/bin/bash LANG=C.UTF-8 PYTHONPATH=:/opt/insightcae/lib/python3.6/site-packages bash -lc source /opt/insightcae/bin/insight_setenv.sh;source insight.bashrc.of1806;cd "/home/user/iroaAHTO";reconstructPar "-latestTime" 
/*---------------------------------------------------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  v1806                                 |
|   \\  /    A nd           | Web:      www.OpenFOAM.com                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
Build  : v1806-17db0a5e0ee7
Arch   : "LSB;label=32;scalar=64"
Exec   : reconstructPar -latestTime
Date   : Mar 03 2024
Time   : 21:36:43
Host   : "DESKTOP-PEBIS6D"
PID    : 7320
I/O    : uncollated
Case   : /home/user/iroaAHTO
nProcs : 1
trapFpe: Floating point exception trapping enabled (FOAM_SIGFPE).
fileModificationChecking : Monitoring run-time modified files using timeStampMaster (fileModificationSkew 10)
allowSystemOperations : Allowing user-supplied system call operations

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
Create time

Reconstructing fields for mesh region0

127.0.0.1 - - [2024-Mar-03 21:36:43.509] "GET /all HTTP/1.1" 200 2252
127.0.0.1 - - [2024-Mar-03 21:36:44.512] "GET /all HTTP/1.1" 200 273
127.0.0.1 - - [2024-Mar-03 21:36:45.514] "GET /all HTTP/1.1" 200 272
Time = 429

Reconstructing FV fields

    Reconstructing volScalarFields

        p
127.0.0.1 - - [2024-Mar-03 21:36:46.517] "GET /all HTTP/1.1" 200 391
        nut
        k
        omega
127.0.0.1 - - [2024-Mar-03 21:36:47.520] "GET /all HTTP/1.1" 200 323

    Reconstructing volVectorFields

        U
127.0.0.1 - - [2024-Mar-03 21:36:48.523] "GET /all HTTP/1.1" 200 339

    Reconstructing surfaceScalarFields

        phi
127.0.0.1 - - [2024-Mar-03 21:36:49.526] "GET /all HTTP/1.1" 200 345
127.0.0.1 - - [2024-Mar-03 21:36:50.529] "GET /all HTTP/1.1" 200 272

Reconstructing point fields

No point fields

No lagrangian fields

No FA fields

End

Overall progress: 85.7143%
Overall: Evaluating results
Overall: Generating mesh quality report
env -i HOME=/home/user USER=user SHELL=/bin/bash LANG=C.UTF-8 PYTHONPATH=:/opt/insightcae/lib/python3.6/site-packages bash -lc source /opt/insightcae/bin/insight_setenv.sh;source insight.bashrc.of1806;cd "/home/user/iroaAHTO";checkMesh "-latestTime" 
/*---------------------------------------------------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  v1806                                 |
|   \\  /    A nd           | Web:      www.OpenFOAM.com                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
Build  : v1806-17db0a5e0ee7
Arch   : "LSB;label=32;scalar=64"
Exec   : checkMesh -latestTime
Date   : Mar 03 2024
Time   : 21:36:51
Host   : "DESKTOP-PEBIS6D"
PID    : 8207
I/O    : uncollated
Case   : /home/user/iroaAHTO
nProcs : 1
trapFpe: Floating point exception trapping enabled (FOAM_SIGFPE).
fileModificationChecking : Monitoring run-time modified files using timeStampMaster (fileModificationSkew 10)
allowSystemOperations : Allowing user-supplied system call operations

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
Create time

Create mesh for time = 429

127.0.0.1 - - [2024-Mar-03 21:36:51.532] "GET /all HTTP/1.1" 200 2301
127.0.0.1 - - [2024-Mar-03 21:36:52.535] "GET /all HTTP/1.1" 200 273
Time = 429

Mesh stats
    points:           414183
    faces:            1140919
    internal faces:   1104764
    cells:            364311
    faces per cell:   6.1641921
    boundary patches: 7
    point zones:      0
    face zones:       0
    cell zones:       0

Overall number of cells of each type:
    hexahedra:     328583
    prisms:        2962
    wedges:        0
    pyramids:      0
    tet wedges:    153
    tetrahedra:    0
    polyhedra:     32613
    Breakdown of polyhedra by number of faces:
        faces   number of cells
            4   1279
            5   905
            6   5223
            7   9789
            8   2754
            9   9290
           10   63
           11   18
           12   2261
           13   6
           14   1
           15   959
           18   61
           21   4

Checking topology...
    Boundary definition OK.
    Cell to face addressing OK.
    Point usage OK.
    Upper triangular ordering OK.
    Face vertices OK.
    Number of regions: 1 (OK).

Checking patch topology for multiply connected surfaces...
                   Patch    Faces   Points                  Surface topology
                   floor    12182    12856  ok (non-closed singly connected)
                   inlet      144      171  ok (non-closed singly connected)
                  outlet      144      171  ok (non-closed singly connected)
                   side1      328      378  ok (non-closed singly connected)
                   side2      328      378  ok (non-closed singly connected)
                     top      738      798  ok (non-closed singly connected)
                  object    22291    24129  ok (non-closed singly connected)

Checking faceZone topology for multiply connected surfaces...
    No faceZones found.

Checking basic cellZone addressing...
    No cellZones found.

Checking geometry...
    Overall domain bounding box (-0.13618265 -0.10213698 0) (0.364438 0.10213698 0.10213698)
    Mesh has 3 geometric (non-empty/wedge) directions (1 1 1)
    Mesh has 3 solution (non-empty) directions (1 1 1)
    Boundary openness (-6.2787919e-18 7.8254882e-17 -1.50465e-15) OK.
    Max cell openness = 3.3311999e-16 OK.
    Max aspect ratio = 11.762368 OK.
    Minimum face area = 9.6017803e-10. Maximum face area = 0.0013363341.  Face area magnitudes OK.
    Min volume = 2.521609e-13. Max volume = 4.7946275e-05.  Total volume = 0.010442054.  Cell volumes OK.
    Mesh non-orthogonality Max: 74.924509 average: 9.2963346
   *Number of severely non-orthogonal (> 70 degrees) faces: 24.
    Non-orthogonality check OK.
  <<Writing 24 non-orthogonal faces to set nonOrthoFaces
    Face pyramids OK.
    Max skewness = 3.7593576 OK.
    Coupled point location match (average 0) OK.

Mesh OK.

End

127.0.0.1 - - [2024-Mar-03 21:36:53.538] "GET /all HTTP/1.1" 200 3447
9.6017803e-10
9.6017803e-10
2.521609e-13
2.521609e-13
Overall: Inserting derived input quantities into report
Overall/Evaluation progress: 0%
"floor"
"inlet"
"object"
"outlet"
"side1"
"side2"
"top"
Overall/Evaluation: Computing projected area
env -i HOME=/home/user USER=user SHELL=/bin/bash LANG=C.UTF-8 PYTHONPATH=:/opt/insightcae/lib/python3.6/site-packages bash -lc source /opt/insightcae/bin/insight_setenv.sh;source insight.bashrc.of1806;cd "/home/user/iroaAHTO";projectedArea "( object )" "(1 0 0)" "-latestTime" 
/*---------------------------------------------------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  v1806                                 |
|   \\  /    A nd           | Web:      www.OpenFOAM.com                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
Build  : v1806-17db0a5e0ee7
Arch   : "LSB;label=32;scalar=64"
Exec   : projectedArea ( object ) (1 0 0) -latestTime
Date   : Mar 03 2024
Time   : 21:36:54
Host   : "DESKTOP-PEBIS6D"
PID    : 9094
I/O    : uncollated
Case   : /home/user/iroaAHTO
nProcs : 1
trapFpe: Floating point exception trapping enabled (FOAM_SIGFPE).
fileModificationChecking : Monitoring run-time modified files using timeStampMaster (fileModificationSkew 10)
allowSystemOperations : Allowing user-supplied system call operations

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
Create time

Create mesh for time = 429

127.0.0.1 - - [2024-Mar-03 21:36:54.545] "GET /all HTTP/1.1" 200 2452
>>

I logged in the VM to check in the work directory. The analyze.log file contains at the end:
<<
*** The analysis was stopped due to this error:

+====================== *** ERROR [139698381321088] *** =======================+
|                                                                              |
| Mat::col(): index out of bounds                                              |
|                                                                              |
+------------------------------------------------------------------------------+
>>

Regards,
Julien

**Comment by hkroeger** [comment]
Dear Julien,
Thanks for the report! I'll check and get back ASAP.

**Comment by hkroeger** [comment]
Dear Julien,

there was a mistake in the simulation app: in the evaluation step, it looked for the results of the forces function object under a wrong name and thus did find only an empty forces vs. time table.
This is now corrected by commit [3340881951c4953e8d7c798ff66be4636fe09faa](https://github.com/hkroeger/insightcae/commit/3340881951c4953e8d7c798ff66be4636fe09faa) and an updated installer is available (5.0.4).

There is no automatic update in Windows yet: you need to download the newer installer, execute it and only check the last component for installation (InsightCAE for Windows). The WSL backend update should then be triggered upon the first start of the workbench via the common linux repository channel.

**Comment by hkroeger** [comment]
Please feel free to reopen, if you encounter issues.
