### ISSUE TITLE
Error occured during Installation of insight cae on win10

### ISSUE THREAD

**Issue by jiayxxh** [hkroeger/insightcae#35]
Hi

I installed the insightcae on Linux system. The default analysis type are different from the tutorial, the shape one which used free surface. Just so ask how I can get those analysis case. Thank you 

regards
Jas

**Comment by hkroeger** [comment]
I guess, you refer to this video https://www.youtube.com/watch?v=kxGlFxFQzPE ?

InsightCAE is a framework and supports the creation of simulation apps for a variety of applications. It is not limited nor specialized to ship resistance problems. The free distribution contains all the building bricks for creating these simulation apps. The simulation apps itself are created and tailored customer-specific.

For the marine field, we have created already add-ons for ship resistance, ship seakeeping analysis and external wind aerodynamics. We distribute these addons only along with a service contract for at least one year. The service includes an initial one-day (online) training, continuous counseling for using the software, provision of updates and even modifications of the software to better suit your needs.
