### ISSUE TITLE
isofCaseBuilder: symbol lookup error in Ubuntu Bionic

### ISSUE THREAD

**Issue by mgsreenath** [hkroeger/insightcae#4]
I have installed insightcae using the binaries provided in `http://downloads.silentdynamics.de/ubuntu`. When I try to run `isofCaseBuilder`, I get the following error.

    isofCaseBuilder: symbol lookup error: /usr/lib/libinsightcad.so: undefined symbol:_ZNK26SelectMgr_SelectableObject12HasSelectionEi

 I did not get any errors during installation.  My OS details are

    NAME="Linux Mint"
    VERSION="19 (Tara)"
    ID=linuxmint
    ID_LIKE=ubuntu
    PRETTY_NAME="Linux Mint 19"
    VERSION_ID="19"
    HOME_URL="https://www.linuxmint.com/"
    SUPPORT_URL="https://forums.ubuntu.com/"
    BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
    PRIVACY_POLICY_URL="https://www.linuxmint.com/"
    VERSION_CODENAME=tara
    UBUNTU_CODENAME=bionic

Could anyone please tell me what is causing this error?

**Comment by hkroeger** [comment]
It looks like it is loading with the wrong OpenCASCADE library. It is intended to be used with the package "liboce-insightcae". Is it installed? (it should be automatically) 
Contrary to what the name suggests, "liboce-insightcae" does not contain the community edition but the vanilla OpenCASCADE 7.2.
There are also other package in the ubuntu repositories, which might cause conflict, when they are installed.

**Comment by mgsreenath** [comment]
Thanks for the quick reply.
I had installed `Gmsh` which was using `liboce-foundation11` and `liboce-modeling11`. I purged these packages and `Gmsh`. But I still have the same error when trying to run `isofCaseBuilder`.

**Comment by mgsreenath** [comment]
I purged `insightcae` and did a fresh install and everything worked fine. Thank you very much.
