### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by ofrikutchinsky** [hkroeger/insightcae#8]
Hi, im trying to install InsightCAE. went through all the instructions-
![image](https://user-images.githubusercontent.com/54778416/64081102-12799800-cd05-11e9-8aec-9e595d0afcab.png)

when trying to open the workbench i get the following error -
QXcbConnection: Could not connect to display
Aborted (core dumped)

![image](https://user-images.githubusercontent.com/54778416/64081163-d09d2180-cd05-11e9-941a-e55cc3ab70ab.png)

Help.. thank you !

**Comment by hkroeger** [comment]
Dear ofrikutchinsky,

Is this an installation in the Linux Subsystem of Windows? Did you install a X-server (this is an independent piece of software)?
If yes, please check whether the DISPLAY environment variable is set:
echo $DISPLAY
It should look like 
:0
or
localhost:0

If it is empty (and a X-server is running), try to set it manually by
export DISPLAY=:0
and retry.

This is also described on our website:
![Auswahl_238](https://user-images.githubusercontent.com/2007077/64081207-4d2c0200-ccfe-11e9-915e-25342c5f21f0.png)

Hope, this helps.

Regards, Hannes

**Comment by ofrikutchinsky** [comment]
hi ! 
X-server is installed. echo $DISPLAY did show up empty, i set it up manually as you said. 
now it shows a different error-

![image](https://user-images.githubusercontent.com/54778416/64081699-2628fc80-cd0d-11e9-97d7-d805b4ef5376.png)

Thank you so much !!
ofri

**Comment by hkroeger** [comment]
Hi again,

on our testmachine, we see these errors on the console as well, but they are not fatal.
Though e.g. the Case Builder is not working properly, seemingly because of a missing window manager.

If Xming is started with the option "-multiwindow" ( see e.g. http://www.straightrunning.com/XmingNotes/manual.php ), everything works fine here.

Regards, Hannes

**Comment by hkroeger** [comment]
Does it work for you with the "-multiwindow" option?

**Comment by ofrikutchinsky** [comment]
hi! didnt see youre answer, thank you !
ofri

‫בתאריך יום ה׳, 5 בספט׳ 2019 ב-10:58 מאת ‪Hannes Kroeger‬‏ <‪
notifications@github.com‬‏>:‬
